FROM ubuntu:22.04
MAINTAINER Alberto Soragna alberto dot soragna at gmail dot com

# working directory
ENV HOME /root
WORKDIR $HOME

# create an empty .bashrc file
RUN touch $HOME/.bashrc
RUN > $HOME/.bashrc

# general utilities
RUN apt-get update && apt-get install -y \
  apt-utils \
  curl \
  nano \
  locales \
  lsb-release \
  gnupg2

# install gcc11 compiler and toolchain
RUN apt-get install -y \
  gcc-11 \
  g++-11 \
  gcc-11-aarch64-linux-gnu \
  g++-11-aarch64-linux-gnu

# set gcc6 as default compiler
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11

#### ROS2

RUN locale-gen en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

RUN curl https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | apt-key add -
RUN sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu jammy main" > /etc/apt/sources.list.d/ros2-latest.list'

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata

# ROS setup requirements + dev tools
RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  python3-flake8-docstrings \
  python3-pip \
  python3-pytest-cov \
  ros-dev-tools \
  software-properties-common \
  git

COPY cross_compile.sh /root
COPY rpi4_toolchainfile.cmake /root

VOLUME [ "/root/ros2_ws" ]
WORKDIR /root/ros2_ws

CMD [ "bash", "/root/cross_compile.sh" ]